declare var _default: {
    new (object: any, domElement: any): {
        object: any;
        domElement: any;
        enabled: boolean;
        screen: {
            left: number;
            top: number;
            width: number;
            height: number;
        };
        rotateSpeed: number;
        zoomSpeed: number;
        panSpeed: number;
        noRotate: boolean;
        noZoom: boolean;
        noPan: boolean;
        noCustom: boolean;
        forceState: number;
        staticMoving: boolean;
        dynamicDampingFactor: number;
        minDistance: number;
        maxDistance: number;
        keys: number[];
        target: Vector3;
        target0: Vector3;
        position0: any;
        up0: any;
        handleResize: () => void;
        handleEvent: (event: any) => void;
        rotateCamera: () => void;
        zoomCamera: () => void;
        panCamera: () => void;
        checkDistances: () => void;
        update: () => void;
        reset: () => void;
        setState: (targetState: any) => void;
        custom: (customStart: any, customEnd: any) => void;
        dispose: () => void;
        addEventListener<T extends string>(type: T, listener: import("three").EventListener<import("three").Event, T, any>): void;
        hasEventListener<T_1 extends string>(type: T_1, listener: import("three").EventListener<import("three").Event, T_1, any>): boolean;
        removeEventListener<T_2 extends string>(type: T_2, listener: import("three").EventListener<import("three").Event, T_2, any>): void;
        dispatchEvent(event: import("three").Event): void;
    };
};
export default _default;
export function trackball(): {
    new (object: any, domElement: any): {
        object: any;
        domElement: any;
        enabled: boolean;
        screen: {
            left: number;
            top: number;
            width: number;
            height: number;
        };
        rotateSpeed: number;
        zoomSpeed: number;
        panSpeed: number;
        noRotate: boolean;
        noZoom: boolean;
        noPan: boolean;
        noCustom: boolean;
        forceState: number;
        staticMoving: boolean;
        dynamicDampingFactor: number;
        minDistance: number;
        maxDistance: number;
        keys: number[];
        target: Vector3;
        target0: Vector3;
        position0: any;
        up0: any;
        handleResize: () => void;
        handleEvent: (event: any) => void;
        rotateCamera: () => void;
        zoomCamera: () => void;
        panCamera: () => void;
        checkDistances: () => void;
        update: () => void;
        reset: () => void;
        setState: (targetState: any) => void;
        custom: (customStart: any, customEnd: any) => void;
        dispose: () => void;
        addEventListener<T extends string>(type: T, listener: import("three").EventListener<import("three").Event, T, any>): void;
        hasEventListener<T_1 extends string>(type: T_1, listener: import("three").EventListener<import("three").Event, T_1, any>): boolean;
        removeEventListener<T_2 extends string>(type: T_2, listener: import("three").EventListener<import("three").Event, T_2, any>): void;
        dispatchEvent(event: import("three").Event): void;
    };
};
import { Vector3 } from "three/src/math/Vector3";
//# sourceMappingURL=controls.trackball.d.ts.map